
export const MY_PRODUCTS_DELETE = 'MY_PRODUCTS_DELETE';
export const MY_PRODUCTS_FETCH = 'MY_PRODUCTS_FETCH';
export const MY_PRODUCTS_FETCH_SUCCESS = 'MY_PRODUCTS_FETCH_SUCCESS';
export const MY_PRODUCTS_UPDATE = 'MY_PRODUCTS_UPDATE'; 
export const STATE_UPDATE = 'STATE_UPDATE'; 
